// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MonitoreoGUI;
//
//    var objeto = Objeto.FromJson(jsonString);

namespace MonitoreoGUI
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Objeto
    {
        [JsonProperty("nombreServidor")]
        public string NombreServidor { get; set; }

        [JsonProperty("encargados")]
        public List<string> Encargados { get; set; }
    }

    public partial class Objeto
    {
        public static Objeto FromJson(string json) => JsonConvert.DeserializeObject<Objeto>(json, MonitoreoGUI.Converter.Settings);
    }

    public static class SerializeObj
    {
        public static string ToJson(this Objeto self) => JsonConvert.SerializeObject(self, MonitoreoGUI.Converter.Settings);
    }

    internal static class ConverterObj
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
