// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MonitoreoGUI;
//
//    var servicio = Servicio.FromJson(jsonString);

namespace MonitoreoGUI
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Servicio
    {
        [JsonProperty("codigoServicio")]
        public long CodigoServicio { get; set; }

        [JsonProperty("codigo")]
        public long Codigo { get; set; }

        [JsonProperty("nombre")]
        public string Nombre { get; set; }

        [JsonProperty("descripcion")]
        public string Descripcion { get; set; }

        [JsonProperty("timeout")]
        public long Timeout { get; set; }

        [JsonProperty("tipo")]
        public string Tipo { get; set; }
    }

    public partial class Servicio
    {
        public static List<Servicio> FromJson(string json) => JsonConvert.DeserializeObject<List<Servicio>>(json, MonitoreoGUI.Converter.Settings);
    }

    public static class SerializeServicio
    {
        public static string ToJson(this List<Servicio> self) => JsonConvert.SerializeObject(self, MonitoreoGUI.Converter.Settings);
    }

    internal static class ConverterServicio
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
