// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MonitoreoGUI;
//
//    var servidor = Servidor.FromJson(jsonString);

namespace MonitoreoGUI
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Servidor
    {
        [JsonProperty("codigo")]
        public long Codigo { get; set; }

        [JsonProperty("nombre")]
        public string Nombre { get; set; }

        [JsonProperty("descripcion")]
        public object Descripcion { get; set; }

        [JsonProperty("usuarioAdmin")]
        public string UsuarioAdmin { get; set; }

        [JsonProperty("contrasena")]
        public string Contrasena { get; set; }

        public string ToJsonString()
        {
            return JsonConvert.SerializeObject(this, Formatting.None);
        }

        public override string ToString()
        {
            return ToJsonString();
        }
    }

    public partial class Servidor
    {
        public static List<Servidor> FromJson(string json) => JsonConvert.DeserializeObject<List<Servidor>>(json, MonitoreoGUI.Converter.Settings);
    }

    public static class SerializeServidor
    {
        public static string ToJson(this List<Servidor> self) => JsonConvert.SerializeObject(self, MonitoreoGUI.Converter.Settings);
    }

    internal static class ConverterServidor
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
