// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MonitoreoGUI;
//
//    var umbralComponente = UmbralComponente.FromJson(jsonString);

namespace MonitoreoGUI
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class UmbralComponente
    {
        [JsonProperty("codigo")]
        public long Codigo { get; set; }

        [JsonProperty("codigoC")]
        public long CodigoC { get; set; }

        [JsonProperty("codigoUmbral")]
        public long CodigoUmbral { get; set; }

        [JsonProperty("porcentaje")]
        public long Porcentaje { get; set; }
    }

    public partial class UmbralComponente
    {
        public static List<UmbralComponente> FromJson(string json) => JsonConvert.DeserializeObject<List<UmbralComponente>>(json, MonitoreoGUI.Converter.Settings);
    }

    public static class SerializeUmbral
    {
        public static string ToJson(this List<UmbralComponente> self) => JsonConvert.SerializeObject(self, MonitoreoGUI.Converter.Settings);
    }

    internal static class ConverterUmbral
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
