// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MonitoreoGUI;
//
//    var usuarios = Usuarios.FromJson(jsonString);

namespace MonitoreoGUI
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Usuarios
    {
        [JsonProperty("usuario")]
        public string Usuario { get; set; }

        [JsonProperty("correo")]
        public string Correo { get; set; }

        [JsonProperty("contrasena")]
        public string Contrasena { get; set; }

        public string ToJsonString()
        {
            return JsonConvert.SerializeObject(this, Formatting.None);
        }

        public override string ToString()
        {
            return ToJsonString();
        }
    }

    public partial class Usuarios
    {
        public static List<Usuarios> FromJson(string json) => JsonConvert.DeserializeObject<List<Usuarios>>(json, MonitoreoGUI.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<Usuarios> self) => JsonConvert.SerializeObject(self, MonitoreoGUI.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
