//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPrograV.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncargadoServidor
    {
        public string Usuario { get; set; }
        public int Codigo { get; set; }
        public Nullable<bool> Notificaciones { get; set; }
    
        public virtual Servidor Servidor { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
